name: Build
run-name: "Build #${{ github.run_number }}"

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b
        with:
          distribution: 'jetbrains'
          java-version: 17
          cache: 'gradle'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: 📦 createDistributable
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            chmod +x ./gradlew
            ./gradlew createDistributable
          elif [ "$RUNNER_OS" == "Windows" ]; then
            ./gradlew.bat createDistributable
          elif [ "$RUNNER_OS" == "macOS" ]; then
            chmod +x ./gradlew
            ./gradlew createDistributable
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Distributable
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: build/compose/binaries/main/app/
